name: Build pvpstats

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pvpstats

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install modules
      run: yarn install && ls -l ./node_modules

    - name: Build
      run: node_modules/.bin/webpack
      env:
        minify: true
