name: Build manifest

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manifest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install modules
      run: yarn install

    - name: Build
      run: node convert2.js
      run: ls -la

    - name: Save
      uses: actions/upload-artifact@v4
      with:
        name: manifest
        path: manifest.js
