name: Build and deploy pvpstats

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v4

    - name: Copy files
      shell: bash
      run: |
        mkdir ./deploy
        cp -r ./pvpstats/src/images ./deploy/
        cp -r ./pvpstats/src/style.css ./deploy/style.css
        cp -r ./pvpstats/src/404.html ./deploy/
        cp -r ./pvpstats/src/index.html.example ./deploy/index.html
        cp -r ./pvpstats/src/proxy.php.example ./deploy/proxy.php
        sed -i "s/BUNGIE_API_KEY/${{secrets.BUNGIE_API_KEY}}/g" ./deploy/proxy.php
        cp ./deploy/proxy.php ./deploy/proxy.txt

    - name: Save
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./deploy/proxy.txt
        if-no-files-found: error
        retention-days: 1
